### ISSUE TITLE
API ключ в сорс кода :/ (security risk)

### ISSUE THREAD

**Issue by DimitarBogdanov** [IvaAMarinova/Affinity#3]
Става въпрос за ето този ред:
https://github.com/IvaAMarinova/Affinity/commit/884b798596cbd18890a4b1095c649209660de7a3#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R111

А именно:
```
newsapi = NewsApiClient(...)
```

Не бива да си държите ключовете в публично качен код. Това най-вероятно е безплатният им developer plan ключ, но пък той от своя страна има ограничение от 100 заявки за ден, т.е. някой с злонамерени мисли може окончателно да ви прецака програмата без да знаете, като просто отдели 5 минути да направи малка програмка, която праща по 100 заявки на ден.

NewsAPI поради някаква причина не позволява да се създаде нов ключ за един акаунт (или поне аз не открих как), което е кофти, защото този ключ вече няма как да бъде скрит (тъй като всички предишни комити с него си остават качени). Тоест, най-вероятно ще ви трябва нов акаунт в newsapi.org, но това вече си е лично ваша работа.

**Важно е да се скрие този и всички други ключове, които може да използвате в бъдеще** - особено ако плащате за тях. За целта се ползва environment файл, който се добавя в gitignore-а (за да не се индексира от git). Ето една малка статия за env файловете и как се ползват в Python: [линк](https://dev.to/jakewitcher/using-env-files-for-environment-variables-in-python-applications-55a1).

Ето една изпратена заявка с вашия ключ:
![image](https://user-images.githubusercontent.com/27803292/162574963-d5d3b04b-898f-435b-8d97-aea85398bf40.png)

**Comment by IvaAMarinova** [comment]
фикснато! мерси много, не бях обърнала внимание :(
